#!/bin/bash
# Prove that ci/check-deps.sh still refuses what it claims to refuse.
#
# Each case writes a small lockfile, a saved `cargo tree` of the shipped
# graph and an allow-list, changes one thing, and asserts the verdict. A
# grep over Cargo.lock that has stopped matching prints "ok" forever, and
# the lockfile format is cargo's to change.
set -u

root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
script="$root/ci/check-deps.sh"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

status=0
cases=0

# A package entry in lockfile format: pkg <name> [dependency...]
pkg() {
    local name=$1
    shift
    printf '[[package]]\nname = "%s"\nversion = "1.0.0"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\n' "$name"
    if [[ $# -gt 0 ]]; then
        printf 'dependencies = [\n'
        for d in "$@"; do printf ' "%s",\n' "$d"; done
        printf ']\n'
    fi
    printf '\n'
}

# The baseline: what the real graph has in the shape that matters.
stage() {
    {
        printf '# This file is automatically @generated by Cargo.\nversion = 4\n\n'
        pkg sukkula-ffi sukkula-engine tokio
        pkg sukkula-engine dbus tokio
        pkg dbus libdbus-sys
        pkg libdbus-sys pkg-config
        pkg pkg-config
        pkg tokio
        pkg rustls ring
        pkg ring
        pkg proptest rusty-fork
        pkg rusty-fork wait-timeout
        pkg wait-timeout
        pkg security-framework
    } > "$work/Cargo.lock"
    cat > "$work/tree" <<'EOF'
sukkula-ffi v0.1.0 (/src/crates/sukkula-ffi)|default
dbus v0.9.12|
libdbus-sys v0.2.7|default,pkg-config
pkg-config v0.3.34|
tokio v1.53.1|bytes,default,full,net,process,rt,sync
rustls v0.23.45|ring,std,tls12
ring v0.17.14|alloc,default
EOF
    cp "$root/ci/deps-allow.conf" "$work/allow"
    return 0
}

run() { "$script" --lock "$work/Cargo.lock" --tree "$work/tree" --allow "$work/allow"; }

# expect <pass|fail> <what> <script run in $work>
expect() {
    local want=$1 what=$2 change=$3 got out
    cases=$((cases + 1))
    stage
    ( cd "$work" && eval "$change" ) || { echo "selftest: FAIL could not apply '$what'" >&2; status=1; return 0; }
    if out=$(run 2>&1); then got=pass; else got=fail; fi
    if [[ "$got" = "$want" ]]; then
        echo "selftest: ok   $what -> $want"
    else
        echo "selftest: FAIL $what should $want, got $got" >&2
        echo "$out" >&2
        status=1
    fi
    return 0
}

# shellcheck disable=SC2016 # the case scripts are expanded by eval, later
{
expect pass "the baseline graph" ':'
expect fail "openssl-sys in the lockfile" 'pkg openssl-sys >> Cargo.lock'
expect fail "native-tls in the lockfile" 'pkg native-tls >> Cargo.lock'
expect fail "aws-lc-rs, a second crypto provider" 'pkg aws-lc-rs aws-lc-sys >> Cargo.lock'
expect fail "zbus, a second D-Bus stack" 'pkg zbus zvariant >> Cargo.lock'
expect fail "async-std, a third async runtime" 'pkg async-std >> Cargo.lock'
expect fail "libdbus-sys built vendored" \
    'sed -i "/^name = \"libdbus-sys\"/,/^\$/ s/ \"pkg-config\",/ \"cc\",\n \"pkg-config\",/" Cargo.lock'
# S8 through libdbus: the engine's connection code is the only code
# clippy.toml's D-Bus constructor bans reach, so nothing else may use dbus
# (finding "S8 gate does not cover libdbus").
expect fail "a dependency that uses dbus itself" 'pkg notify-rust dbus >> Cargo.lock'
expect fail "a dependency naming dbus by version" 'pkg notify-rust "dbus 0.9.12" >> Cargo.lock'
expect fail "a crate using libdbus-sys around the dbus crate" 'pkg dbus-sys-user libdbus-sys >> Cargo.lock'
expect fail "the FFI crate using dbus directly" 'sed -i "s/^ \"sukkula-engine\",\$/ \"sukkula-engine\",\n \"dbus\",/" Cargo.lock'
expect pass "a crate whose name only starts with dbus" 'pkg other "dbus-codegen" >> Cargo.lock && pkg dbus-codegen >> Cargo.lock'
expect fail "dbus' vendored feature in the phone build" \
    'sed -i "s/^dbus v0.9.12|\$/dbus v0.9.12|vendored/" tree'
expect fail "bluer without an allow entry" 'pkg bluer >> Cargo.lock'
expect pass "bluer with a ship allow entry" \
    'pkg bluer >> Cargo.lock; echo "bluer v0.17.0|" >> tree; echo "bluer ship BLE nudge (test)" >> allow'
expect fail "bluer allowed for tests only but shipped" \
    'pkg bluer >> Cargo.lock; echo "bluer v0.17.0|" >> tree; echo "bluer dev tests only (test)" >> allow'
expect fail "async-process without an allow entry" 'pkg async-process >> Cargo.lock'
# S8's other half, no opening: every crate here exists to hand a URL or a
# file to xdg-open, a browser or a shell (finding "check-deps' S8 denylist
# lets URL/file-opening and spawning crates into the shipped graph").
for crate in open opener webbrowser that showfile xdg-utils \
             duct subprocess xshell cmd_lib portable-pty pty-process nix; do
    expect fail "$crate in the lockfile without an allow entry" "pkg $crate >> Cargo.lock"
done
expect fail "webbrowser in the phone build, allowed for tests only" \
    'pkg webbrowser >> Cargo.lock; echo "webbrowser v1.0.0|" >> tree; echo "webbrowser dev a test helper (test)" >> allow'
expect pass "opener in the lockfile for tests only, with a dev entry" \
    'pkg opener >> Cargo.lock; echo "opener dev a test helper (test)" >> allow'
expect fail "a dev-only process crate reaching the phone build" 'echo "rusty-fork v0.3.0|" >> tree'
expect fail "tokio's process feature with no allow entry" 'sed -i "/^tokio\/process/d" allow'
expect fail "a platform TLS binding in the phone build" 'echo "security-framework v3.7.0|" >> tree'
expect fail "a stale allow entry" 'echo "duct dev nothing uses this" >> allow'
expect fail "an allow entry for a crate refused outright" \
    'pkg openssl >> Cargo.lock; echo "openssl ship we want it" >> allow'
expect fail "an allow entry with no scope" 'echo "duct" >> allow; pkg duct >> Cargo.lock'
expect fail "an allow entry with no reason" 'echo "duct dev" >> allow; pkg duct >> Cargo.lock'
expect fail "an empty shipped graph" ': > tree'
}

# And the real lockfile, as far as it can be read without cargo.
cases=$((cases + 1))
if out=$("$script" --lock-only 2>&1); then
    echo "selftest: ok   the committed Cargo.lock -> pass"
else
    echo "selftest: FAIL the committed Cargo.lock fails check-deps:" >&2
    echo "$out" >&2
    status=1
fi

echo
if [[ "$status" -eq 0 ]]; then
    echo "selftest: ok ($cases cases)"
else
    echo "selftest: FAILED" >&2
fi
exit "$status"
